const app = document.querySelector('#app');
const connection = document.querySelector('#connection');
const dot = document.querySelector('.live-dot');
const badge = document.querySelector('#task-badge');
const updated = document.querySelector('#updated');
const nav = [...document.querySelectorAll('[data-route]')];
const cache = { overview: null };
let currentController = null;
let pollTimer = null;
let inFlight = false;
let route = 'overview';
let taskOffset = 0;
let taskState = '';
let search = '';
let selectedTask = null;
let selectedTrace = null;
let lastSuccess = 0;
let pollDelay = 5000;
let logOffset = 0;
let logFilter = '';
let logRefreshTimer = null;

function el(tag, cls, value) { const node = document.createElement(tag); if (cls) node.className = cls; if (value !== undefined) node.textContent = String(value); return node; }
function add(parent, child) { parent.append(child); return child; }
function anchor(href, text, cls = '') { const node = el('a', cls, text); node.href = href; return node; }
function card(title, span = 'span-4') { const c = el('section', `card ${span}`); c.setAttribute('aria-label', title); add(c, el('h2', 'card-title', title)); return c; }
function header(kicker, title, sub, stamp = 'LOCAL OWNER VIEW') { const h = el('header', 'page-head'); const left = el('div'); add(left, el('div', 'eyebrow', kicker)); add(left, el('h1', '', title)); if (sub) add(left, el('p', '', sub)); add(h, left); add(h, el('div', 'stamp', stamp)); return h; }
function pill(state) { const p = el('span', 'pill', state || 'UNKNOWN'); const v = String(state || '').toLowerCase(); if (['completed','connected','available','running','on','read-only'].includes(v)) p.classList.add('good'); else if (['failed','ambiguous','disconnected','unavailable','off'].includes(v)) p.classList.add('bad'); else p.classList.add('warn'); return p; }
function fmt(date) { if (!date) return '—'; const d = new Date(date); return Number.isNaN(+d) ? '—' : new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d); }
function row(parent, title, detail, end) { const r = el('div','row'); const main = el('div','row-main'); add(main,el('b','',title)); if(detail) add(main,el('small','',detail)); add(r,main); if(end) add(r,typeof end==='string'?el('div','row-end',end):end); add(parent,r); return r; }
async function api(path, signal) { const response=await fetch(path,{signal,headers:{accept:'application/json'},cache:'no-store'}); if(!response.ok) throw new Error((await response.json().catch(()=>({error:`HTTP ${response.status}`}))).error); return response.json(); }
function setConnection(ok, message) { connection.textContent=message; dot.className=`live-dot ${ok?'ok':'bad'}`; }
function useFreshness(data) { const age=Date.now()-Date.parse(data.generatedAt); const fresh=age<15_000; setConnection(fresh, fresh?`LOCAL API · FRESH · NODE ${data.machine.online?'ONLINE':'OFFLINE'}`:'LOCAL API · STALE'); updated.textContent=`Last update ${fmt(data.generatedAt)}`; badge.textContent=String(data.tasks.active); }
async function refreshOverview(signal) { const data=await api('/api/overview',signal); cache.overview=data; lastSuccess=Date.now(); pollDelay=5000; useFreshness(data); return data; }
function appendAttention(parent, items) { if(!items.length)return; const box=el('section','attention'); add(box,el('h2','','NEEDS ATTENTION')); for(const item of items){const r=el('div','attention-row');add(r,anchor(`#tasks/${encodeURIComponent(item.taskId)}`,item.taskId));add(r,el('span','',`${item.state} · ${item.operation} · ${item.status||''}`));add(box,r);} add(parent,box); }
function renderOverview(data) { app.replaceChildren(); add(app,header('DEX//REACH / OWNER CONSOLE','What needs attention?','A live, local view of the selected machine. No remote node fallback.')); appendAttention(app,data.tasks.attention); const grid=el('div','grid');
 let c=card('MACHINE / IDENTITY','span-4'); add(c,el('div','metric small',data.machine.hostname)); add(c,el('div','sub',`${data.machine.platform} / ${data.machine.arch}`)); add(c,el('div','keyline')); const status=el('div','row');add(status,el('span','muted','Node'));add(status,pill(data.machine.online?'ONLINE':'OFFLINE'));add(c,status); row(c,'Selected node',data.machine.nodeId||'No exact local node identity match'); add(grid,c);
 c=card('AI ACCESS','span-4');add(c,el('div','metric small',data.machine.accessMode||'UNAVAILABLE'));add(c,el('div','sub','Current node policy snapshot'));add(c,el('div','keyline'));add(c,el('div','sub','The web console exposes no policy mutation controls.'));add(grid,c);
 c=card('ACTIVE WORK','span-4');add(c,el('div','metric',data.tasks.active));add(c,el('div','sub',`${data.tasks.waiting===null?'Queue unavailable':`${data.tasks.waiting} in coordinator queue`}`));add(c,el('div','keyline'));add(c,anchor('#tasks','Open task workstation','button'));add(grid,c);
 c=card('MACHINE HEALTH','span-6');row(c,'Gateway',data.machine.runtimeUpdatedAt?`Runtime heartbeat ${fmt(data.machine.runtimeUpdatedAt)}`:'No fresh node heartbeat',pill(data.machine.gateway));row(c,'Coordinator','Local work coordinator',pill(data.machine.coordinator));row(c,'Worker','Process observation only',pill(data.machine.worker));row(c,'Queue / active leases',data.machine.queueDepth===null?'Unavailable':`${data.machine.queueDepth} queued · ${data.machine.activeLeases} active`);add(grid,c);
 c=card('SERVICES','span-6');if(data.services.observed.length){for(const name of data.services.observed)row(c,name,'Observed in local process table',pill('observed'));}else add(c,el('div','empty','No DEX services observed in the process table.'));add(c,el('div','sub','CPU and memory pressure metrics are not available in this view.'));add(grid,c);
 c=card('ACTIVE WORK / RECENT TASKS','span-7');if(data.tasks.recent.length){for(const t of data.tasks.recent){const end=pill(t.state);const r=row(c,t.operation,`${t.taskId} · ${t.nodeId}`,end);r.append(el('div','row-end',fmt(t.updatedAtUtc)));}}else add(c,el('div','empty','No durable tasks recorded.'));add(grid,c);
 c=card('RECENT ACTIVITY','span-5');if(data.activity.length){for(const a of data.activity)row(c,a.operation,`${a.state} · ${a.taskId||'no task link'}`,fmt(a.updatedAt));}else add(c,el('div','empty','No process activity records available.'));add(grid,c);
 c=card('CONNECTOR STATUS','span-6');row(c,'Local backend','This Control Room API',pill(data.connector.localBackend));row(c,'Gateway',data.machine.gateway,pill(data.connector.gateway));row(c,'Public MCP',data.connector.publicMcp);row(c,'ChatGPT exposure',data.connector.chatGptExposure);row(c,'Protocol / declared actions',`${data.connector.protocolVersion} / ${data.connector.expectedPublicActions}`);add(grid,c);
 c=card('PROJECT / DELIVERY STATES','span-6');row(c,'Source',`${data.project.repository} · ${data.project.branch}`,data.project.head.slice(0,12));row(c,'Worktree',data.project.dirty?`${data.project.dirtyCount} changed path(s)`:'clean',pill(data.project.dirty?'uncommitted':'clean'));row(c,'Tested',data.project.tested);row(c,'Committed / pushed',`${data.project.committed} / ${data.project.pushed}`);row(c,'Installed / deployed',`${data.project.installed} / ${data.project.deployed}`);add(grid,c); add(app,grid); }
function renderTasks(payload) { app.replaceChildren();add(app,header('WORKSTATION / DURABLE TASKS','Task ledger','Bounded pages from the authoritative local task store. Details include recorded lifecycle events only.'));const tools=el('div','toolbar');const input=el('input');input.type='search';input.placeholder='Filter this page by task or operation';input.setAttribute('aria-label','Filter tasks on this page');input.value=search;input.addEventListener('input',()=>{search=input.value.toLowerCase();for(const record of c.querySelectorAll('.task-row'))record.hidden=!record.dataset.search.includes(search);});add(tools,input);const select=el('select');select.setAttribute('aria-label','Filter by task state');for(const s of ['',...payload.states]){const o=el('option','',s||'All states');o.value=s;o.selected=taskState===s;add(select,o);}select.addEventListener('change',()=>{taskState=select.value;taskOffset=0;void loadTasks();});add(tools,select);add(app,tools);const c=card('TASK RECORDS','span-12');const shown=payload.items.filter(t=>`${t.taskId} ${t.operation} ${t.state} ${t.nodeId}`.toLowerCase().includes(search));if(!shown.length)add(c,el('div','empty',payload.total?'No tasks match this page filter.':'No durable tasks recorded.'));for(const t of shown){const r=el('div','task-row');r.dataset.search=`${t.taskId} ${t.operation} ${t.state} ${t.nodeId}`.toLowerCase();const identity=el('div');add(identity,anchor(`#tasks/${encodeURIComponent(t.taskId)}`,t.taskId));add(identity,el('small','',`${t.nodeId} · updated ${fmt(t.updatedAtUtc)}`));add(r,identity);const state=el('div','task-state');add(state,pill(t.state));add(r,state);add(r,el('div','task-op',t.operation));add(r,el('div','task-updated muted',t.summary?.status||''));add(c,r);}const page=el('div','pagination');const prev=el('button','button','Previous');prev.disabled=taskOffset===0;prev.addEventListener('click',()=>{taskOffset=Math.max(0,taskOffset- payload.limit);void loadTasks();});add(page,prev);add(page,el('span','muted',`${payload.total?taskOffset+1:0}–${Math.min(taskOffset+payload.items.length,payload.total)} of ${payload.total}`));const next=el('button','button','Next');next.disabled=taskOffset+payload.limit>=payload.total;next.addEventListener('click',()=>{taskOffset+=payload.limit;void loadTasks();});add(page,next);add(c,page);const meta=el('div','sub',`Supported states: ${payload.states.join(', ')}`);add(c,meta);add(app,c); }
async function loadTasks() { currentController?.abort();currentController=new AbortController();try{const q=new URLSearchParams({limit:'20',offset:String(taskOffset)});if(taskState)q.set('state',taskState);const data=await api(`/api/tasks?${q}`,currentController.signal);renderTasks(data);}catch(e){if(e.name!=='AbortError')showError('Task list unavailable',e.message);} }
async function renderTaskDetail(id) { currentController?.abort();currentController=new AbortController();app.replaceChildren();add(app,header('WORKSTATION / TASK DETAIL','Loading task…','Reading task snapshot and recorded event history.'));try{const d=await api(`/api/tasks/${encodeURIComponent(id)}`,currentController.signal);app.replaceChildren();add(app,header(`TASK / ${d.task.state}`,d.task.operation,d.task.taskId));const grid=el('div','grid');const c=card('AUTHORITATIVE SNAPSHOT','span-5');const latest=d.activity[0];const fields=[['State',d.task.state],['Node',d.task.nodeId],['Attempt',`${d.task.attemptNumber} of ${d.task.attemptBudget}`],['Phase',latest?.phase||'Not present in activity evidence'],['Heartbeat evidence',latest?.lastResourceAt?fmt(latest.lastResourceAt):'Not recorded'],['Progress evidence',latest?.lastStdoutAt?fmt(latest.lastStdoutAt):'Not recorded'],['Created',fmt(d.task.createdAtUtc)],['Updated',fmt(d.task.updatedAtUtc)],['Summary',d.task.summary?.status||'Unavailable'],['Failure class',d.task.failureClass||'None recorded'],['Result',d.task.resultAvailable?'Available; payload withheld':'No result reference'],['Trace identity',d.task.traceId||'None linked']];const detail=el('div','detail-grid');for(const [k,v]of fields){const item=el('div','detail-item');add(item,el('label','',k));add(item,el('div','',v));add(detail,item);}add(c,detail);add(c,el('div','sub','Available controls: none through this read-only browser surface.'));add(grid,c);const hist=card('RECORDED LIFECYCLE EVENTS','span-7');if(d.events.length){const timeline=el('div','timeline');for(const ev of [...d.events].reverse()){const entry=el('div','event');add(entry,el('time','',fmt(ev.at)));add(entry,el('b','',`${ev.kind}${ev.state?` · ${ev.state}`:''}${ev.attempt?` · attempt ${ev.attempt}`:''}`));add(entry,el('p','',ev.summary||ev.control||'Recorded event has no summary.'));add(timeline,entry);}add(hist,timeline);}else add(hist,el('div','empty','No lifecycle events are recorded for this task.'));add(grid,hist);add(app,grid);if(d.trace.length){const tc=card('LINKED TRACE','span-12');for(const sp of d.trace)row(tc,sp.stage,`${sp.operation||'step'} · ${sp.outcome|| (sp.ok===undefined?'outcome unavailable':sp.ok?'ok':'failed')}${sp.receiptId?` · receipt ${sp.receiptId}`:''}`,fmt(sp.at));add(app,tc);}}catch(e){if(e.name!=='AbortError')showError('Task detail unavailable',e.message);} }
async function renderLog() {clearTimeout(logRefreshTimer);app.replaceChildren();add(app,header('EVIDENCE / OWNER-LOCAL','LOG / TRACE','Content-free process activity and causal trace records. No command output or private payloads.'));try{const data=await api(`/api/log?limit=20&offset=${logOffset}`);const grid=el('div','grid');const tools=el('div','toolbar');const input=el('input');input.type='search';input.placeholder='Filter this page by task, operation, or trace';input.setAttribute('aria-label','Filter log and trace records on this page');input.value=logFilter;add(tools,input);add(app,tools);let c=card('DEX//LOG · PROCESS ACTIVITY','span-6');const activityRows=[];if(data.activity.length){for(const a of data.activity){const r=row(c,a.operation,`${a.state} · ${a.taskId||'no task link'} · ${a.processLabel}`,fmt(a.startedAt));r.dataset.search=`${a.operation} ${a.taskId||''} ${a.processLabel} ${a.state}`.toLowerCase();activityRows.push(r);}}else add(c,el('div','empty','No process activity records available.'));add(grid,c);c=card('DEX//TRACE · RECENT CAUSAL RECORDS','span-6');const traceRows=[];if(data.traces.length){for(const t of data.traces){const r=el('div','row');r.dataset.search=`${t.traceId}`.toLowerCase();const b=el('button','trace-list mono',`${t.traceId} · ${t.spans} spans · ${fmt(t.at)}`);b.type='button';b.addEventListener('click',()=>{selectedTrace=t.traceId;void showTrace(t.traceId,c);});add(r,b);add(c,r);traceRows.push(r);}}else add(c,el('div','empty',data.traceStatus==='loading'?'Indexing the most recent local traces…':'No trace records are available for this node.'));add(grid,c);const filteredPage=el('div','sub',`Page ${Math.floor(logOffset/20)+1} · ${data.activityTotal} activity records · newest 100 local traces`);add(app,grid);add(app,filteredPage);input.addEventListener('input',()=>{logFilter=input.value.toLowerCase();for(const r of [...activityRows,...traceRows])r.hidden=!r.dataset.search.includes(logFilter);});const pager=el('div','pagination');const prev=el('button','button','Previous');prev.disabled=logOffset===0;prev.addEventListener('click',()=>{logOffset=Math.max(0,logOffset-20);void renderLog();});add(pager,prev);const next=el('button','button','Next');next.disabled=data.activity.length<20&&!data.tracesHaveMore;next.addEventListener('click',()=>{logOffset+=20;void renderLog();});add(pager,next);add(app,pager);if(data.traceStatus==='loading')logRefreshTimer=setTimeout(()=>{if(route==='log')void renderLog();},3000);}catch(e){showError('LOG / TRACE unavailable',e.message);} }
async function showTrace(id,parent){try{const data=await api(`/api/traces/${encodeURIComponent(id)}`);const existing=app.querySelector('.trace-detail');existing?.remove();const c=card('TRACE DETAIL · CONTENT-FREE','span-12');c.classList.add('trace-detail');add(c,el('div','mono',id));for(const span of data.spans)row(c,span.stage,`${span.operation||'step'} · task ${span.taskId||'not linked'} · node ${span.nodeId||'not linked'} · ${span.outcome||(span.ok===undefined?'outcome unavailable':span.ok?'ok':'failed')}${span.receiptId?` · receipt ${span.receiptId}`:''}`,fmt(span.at));add(parent,c);}catch(e){showError('Trace unavailable',e.message);}}
function renderMachine(data){app.replaceChildren();add(app,header('MACHINE / SERVICES','Machine health','Data exposed by the owner-local runtime. Missing measurements remain unavailable.'));const grid=el('div','grid');let c=card('SELECTED MACHINE','span-6');row(c,'Hostname',data.machine.hostname);row(c,'Platform / architecture',`${data.machine.platform} / ${data.machine.arch}`);row(c,'Node identity',data.machine.nodeId||'No exact local node identity match');row(c,'Online',data.machine.online?'Fresh runtime heartbeat':'Offline or stale',pill(data.machine.online?'online':'offline'));row(c,'AI access',data.machine.accessMode||'Unavailable',pill(data.machine.accessMode||'unavailable'));row(c,'Runtime revision',data.machine.runtimeVersion);row(c,'Heartbeat',fmt(data.machine.runtimeUpdatedAt));add(grid,c);c=card('SERVICES / CAPACITY','span-6');row(c,'Gateway',data.machine.gateway,pill(data.machine.gateway));row(c,'Coordinator',data.machine.coordinator,pill(data.machine.coordinator));row(c,'Worker',data.machine.worker,pill(data.machine.worker));row(c,'Queue depth',data.machine.queueDepth??'Unavailable');row(c,'Active leases',data.machine.activeLeases??'Unavailable');row(c,'CPU pressure','Unavailable');row(c,'Memory pressure','Unavailable');row(c,'Observed services',data.services.observed.join(', ')||'None observed');add(grid,c);c=card('CONNECTOR / SCHEMA','span-12');row(c,'Local backend','Loopback adapter',pill('available'));row(c,'Public MCP','Not measured by this UI');row(c,'Protocol version',data.connector.protocolVersion);row(c,'Expected public actions',data.connector.expectedPublicActions);row(c,'ChatGPT exposure',data.connector.chatGptExposure);add(grid,c);add(app,grid);}
function showError(title,message){let box=app.querySelector('[data-error-banner]');if(!box){box=el('section','error');box.dataset.errorBanner='true';box.setAttribute('role','alert');app.prepend(box);}box.replaceChildren();add(box,el('b','',title));add(box,el('p','',message));add(box,el('p','',cache.overview?`Last successful refresh ${fmt(cache.overview.generatedAt)}. Displayed snapshot is stale; statuses above are not current.`:'No previous successful response is available.'));setConnection(false,`LOCAL API · ERROR${lastSuccess?` · stale ${Math.floor((Date.now()-lastSuccess)/1000)}s`:''}`);dot.className='live-dot bad';}
async function renderRoute(){nav.forEach(a=>a.classList.toggle('active',a.dataset.route===route));try{if(route==='tasks'&&selectedTask)return await renderTaskDetail(selectedTask);if(route==='tasks')return await loadTasks();if(route==='log')return await renderLog();const data=await refreshOverview(currentController?.signal);if(route==='machine')renderMachine(data);else renderOverview(data);}catch(e){if(e.name!=='AbortError')showError('Local backend unavailable',e.message);}}
function onHash(){const parts=location.hash.slice(1).split('/');route=['overview','tasks','log','machine'].includes(parts[0])?parts[0]:'overview';selectedTask=route==='tasks'&&parts[1]?decodeURIComponent(parts[1]):null;void renderRoute();}
function schedulePoll(){clearTimeout(pollTimer);if(document.hidden)return;pollTimer=setTimeout(async()=>{if(!inFlight){inFlight=true;currentController?.abort();currentController=new AbortController();try{const data=await refreshOverview(currentController.signal);pollDelay=5000;if(route==='overview')renderOverview(data);else if(route==='machine')renderMachine(data);}catch(e){if(e.name!=='AbortError'){pollDelay=Math.min(30000,pollDelay*2);showError('Refresh failed',e.message);}}finally{inFlight=false;}}schedulePoll();},pollDelay);}
document.querySelector('#refresh').addEventListener('click',()=>{currentController?.abort();currentController=new AbortController();void renderRoute();});window.addEventListener('hashchange',onHash);document.addEventListener('visibilitychange',()=>{clearTimeout(pollTimer);if(!document.hidden){void renderRoute();schedulePoll();}});window.addEventListener('pagehide',()=>{clearTimeout(pollTimer);currentController?.abort();},{once:true});onHash();schedulePoll();
